### ISSUE TITLE
[Bug]: Action not triggering another workflow / ignoring GITHUB_TOKEN override

### ISSUE THREAD

**Issue by Bastianowicz** [gembaadvantage/uplift-action#73]
### What happened?

[In my project](https://github.com/Bastianowicz/axios-transform-validate-response) I have to separate workflows.

One is for "[release](https://github.com/Bastianowicz/axios-transform-validate-response/blob/main/.github/workflows/ci.yml)" which is the uplift action triggering uplift release. This action I configured to use a personal access token instead of the GITHUB_TOKEN (like said in the [docs](https://upliftci.dev/ci/github/#triggering-another-workflow)).
❌ This does not seem to work though. The [tags created](https://github.com/Bastianowicz/axios-transform-validate-response/tags) are still authored by uplift bot.

The other is to [publish](https://github.com/Bastianowicz/axios-transform-validate-response/blob/main/.github/workflows/cd.yml) the new version to npm. This does work when I manually push a tag. But it does not automatically after the release pipeline ran since the tags are still being created by the uplift bot.

Further the PAT in the settings says "never used". I regenerated it and added it freshly as an action secret. It does not seem to be applied to the action since it says "never used" nevertheless.

### Steps to reproduce it

```shell
1. Create a workflow "X" that runs on any created tag.
2. Override your Github_token like in the [docs](https://upliftci.dev/ci/github/#triggering-another-workflow)
3. Commit a fix or feat commit and thus run the uplift action

## expected behaviour
* X runs after the uplift action ran
* the tag is authored by you (your PAT)

## experienced
* the tag is still authored by Uplift Bot
* of course the workflow X does not run
```

### Your uplift action configuration

```yaml
  release:
    name: Release
    if: github.ref == 'refs/heads/main' && !startsWith( github.event.commits[0].message, 'build(deps-dev)') && !startsWith( github.event.commits[0].message, 'ci(uplift)')
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Release
        if: github.ref == 'refs/heads/main'
        uses: gembaadvantage/uplift-action@v2.0.1
        with:
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_UPLIFT }}
```

### Which version?

v2.0.1
